server:
  port: 8080

logging:
  config: file:./config/logback-spring-local.xml

spring:
  application:
    name: platform
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:15432/mydatabase
    username: myuser
    password: secret

mybatis:
  mapper-locations:
  - classpath*:sql/*.xml
  - classpath*:sql/**/*.xml
  type-aliases-package: 
    net.herit.platform.platform_spring.features.com.dto.entity.**
    net.herit.platform.platform_spring.features.auth.dto.entity.**
  configuration:
    map-underscore-to-camel-case: true

token:
  issuer: hzems
  access:
    secretkey: hzems$$access.token
    expired:
      minute: 5
#      minute: 120
  refresh:
    secretkey: hzems$$refresh.token
    expired:
      minute: 10080